spring.application.name=naruto-api

spring.datasource.url=jdbc:postgresql://localhost:5432/db_naruto
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.format_sql=true
springdoc.swagger-ui.path=/naruto

server.port=8080